---
- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: Europe/Moscow
  become: true

- name: Upgrade Kernel
  include_tasks: kernel-upgrade.yml

- name: Network config
  include_tasks: "{{ inventory_hostname }}-network.yml"


  