---
- name: Add dns names /etc/hosts
  shell: echo {{ item }} >> /etc/hosts
  loop:
    - "192.168.6.2 db"
    - "192.168.5.1 router"
  become: true

- name: Deploy 50-web.yaml
  copy: 
    src: files/50-web.yaml
    dest: "/etc/netplan"
  become: true

- name: Netplan apply
  shell: netplan apply
  become: true

- name: Install packages
  apt:
    name: 
      - net-tools
    state: latest
    update_cache: yes
  become: true

- name: Up enp0s9
  shell: "ifconfig enp0s9 up"
  become: true

- name: External access
  ansible.builtin.iptables:
    in_interface: enp0s3
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "25"
      - "80"
      - "443"
    jump: ACCEPT
  become: true

# - name: DB access
#   ansible.builtin.iptables:
#     in_interface: enp0s8
#     chain: INPUT
#     protocol: tcp
#     destination_ports:
#       - "5432"
#     jump: ACCEPT
#   become: true

- name: Manage network access (udp)
  ansible.builtin.iptables:
    in_interface: enp0s9
    chain: INPUT
    protocol: udp
    destination_ports:
      - "53"
      - "67"
    jump: ACCEPT
  become: true

- name: Manage network access (tcp)
  ansible.builtin.iptables:
    in_interface: enp0s9
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "53"
      - "22"
      - "3000"
    jump: ACCEPT
  become: true

- name: Node-exporter access (tcp)
  ansible.builtin.iptables:
    in_interface: enp0s8
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "9100"
    jump: ACCEPT
  become: true

- name: Allow lo conections
  ansible.builtin.iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: yes

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes

- name: Set the policy for the INPUT chain to DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
  become: true

- name: Ensure directories exists
  file:
    path: "{{ iptables_dir }}"
    state: directory
    owner: root
    group: root
  become: true

- name: "Deploy {{inventory_hostname}}-iptables.sh"
  copy: 
    src: files/{{inventory_hostname}}-iptables.sh
    dest: "{{ iptables_dir }}"
    owner: root
    group: root
  become: true

- name: Create iptpers.service
  ansible.builtin.template:
    src: templates/iptpers.service
    dest: /etc/systemd/system/iptpers.service
    mode: 0755
  become: true

- name: Enable iptpers.service
  ansible.builtin.systemd:
    name: iptpers
    enabled: yes
    daemon_reload: yes
  become: true