---
- name: Ensure group {{node_exporter_group}} exists
  group:
    name: "{{node_exporter_group}}"
    state: present
  become: true

- name: Add user {{node_exporter_user}}  
  user:
    name: "{{node_exporter_user}}"
    groups: "{{node_exporter_group}}"
    shell: /sbin/nologin
    append: yes
    comment: "Nologin User"
    state: present
  become: true

- name: Ensure {{node_exporter_path}} directory exists
  file:
    path: /opt/node_exporter
    state: directory
  become: true

- name: Download and unarchive node exporter
  ansible.builtin.unarchive:
    src: "{{node_exporter_src}}"
    dest: /opt/node_exporter
    remote_src: yes
  become: true

- name: Create node-exporter.service
  ansible.builtin.template:
    src: templates/node-exporter.service
    dest: /etc/systemd/system/node-exporter.service
    mode: 0755
  become: true

- name: Start and enable node-exporter.service
  ansible.builtin.systemd:
    name: node-exporter
    state: started
    enabled: yes
    daemon_reload: yes
  become: true